<p style="align: center;"><img src="https://upload.wikimedia.org/wikipedia/commons/9/96/Pytorch_logo.png" width=400 height=100></p>

Этот ноутбук посвящён основам  библиотеки PyTorch.

<h3 style="text-align: center;"><b>Введение</b></h3>

В настоящее время существует множество фреймворков глубокого обучения. Разница между ними заключается во внутренних принципах вычислений. Например, в **[Caffe](http://caffe.berkeleyvision.org/)** и **[Caffe2](https://caffe2.ai/)** вы пишете код, используя некоторые «готовые блоки» "(как и $ LEGO ^ {TM} $ :). В **[TensorFlow](https://www.tensorflow.org/)** и **[Theano](http://deeplearning.net/software/theano/)** вы сначала объявляете граф вычислений, затем компилируйте его и используйте для вывода / обучения (`tf.session ()`). Кстати, теперь в TensorFlow (начиная с версии 1.10) есть функция [Eager Execution](https://www.tensorflow.org/guide/eager), которая может быть полезна для быстрого прототипирования и отладки. **[Keras](https://keras.io/)** - очень популярный и полезный фреймворк DL, который позволяет быстро реализовывать нейронный сети и имеет множество полезных функций.


<p style="align: center;"><img src="https://habrastorage.org/web/e3e/c3e/b78/e3ec3eb78d714a7993a6b922911c0866.png" width=500 height=500></p>  
<p style="text-align: center;"><i>Image credit: https://habr.com/post/334380/</i><p>

Мы будем использовать **PyTorch**, поскольку он активно развивается и поддерживается AI-сообществом

<h3 style="text-align: center;"><b>Установка</b></h3>

Подробную инструкцию по установке PyTorch вы можете найти на [официальном сайте PyTorch](https://pytorch.org/).

## Синтаксис Фреймворка

In [1]:
import torch

Несколько фактов о PyTorch:
- динамический граф вычислений
- удобные модули `torch.nn` и `torchvision` для быстрого прототипирования нейронных сетей
- даже быстрее, чем TensorFlow на некоторых задачах
- позволяет легко использовать **GPU**

По своей сути PyTorch предоставляет две основные функции:

- n-мерный тензор, похожий на **numpy**, но может работать на графических процессорах
- Автоматическая дифференциация для построения и обучения нейронных сетей

Если бы PyTorch был формулой, она была бы такой:

$$PyTorch = NumPy + CUDA + Autograd$$

(CUDA - [wiki](https://en.wikipedia.org/wiki/CUDA))

Давайте посмотрим, как мы можем использовать PyTorch для работы с векторами и тензорами.

Напомним, что **тензор** - это многомерный вектор, например :

`x = np.array ([1,2,3])` - вектор = тензор с 1 размерностью (точнее: `(3,)`)

`y = np.array ([[1, 2, 3], [4, 5, 6]])` - матрица = тензор с двумя измерениями (`(2, 3)` в данном случае)

`z = np.array ([[[1, 2, 3], [4, 5, 6], [7, 8, 9]]],
               [[1, 2, 3], [4, 5, 6], [7, 8, 9]],
               [[1, 2, 3], [4, 5, 6], [7, 8, 9]]]) `-" куб "(3, 3, 3) = тензор с тремя измерениями (` ( 3, 3, 3) `в этом случае)


Одним из реальных примеров трехмерного тензора является **изображение**, оно имеет 3 измерения: `высота`, `ширина` и `глубина канала` (глубина канала = 3 для цветных изображений, 1 для оттенков серого). Вы можете думать об этом как о параллелепипеде, состоящем из действительных чисел.


### Типы Тензоров

В PyTorch мы будем использовать `torch.Tensor` (`FloatTensor`, `IntTensor`, `ByteTensor`) для всех вычислений.

Все типы:

In [2]:
torch.HalfTensor      # 16 бит, floating point
torch.FloatTensor     # 32 бита, floating point
torch.DoubleTensor    # 64 бита, floating point

torch.ShortTensor     # 16 бит, integer, signed
torch.IntTensor       # 32 бита, integer, signed
torch.LongTensor      # 64 бита, integer, signed

torch.CharTensor      # 8 бит, integer, signed
torch.ByteTensor      # 8 бит, integer, unsigned

torch.ByteTensor

Мы будем использовать только `torch.FloatTensor()` и `torch.IntTensor()`.

Начнем уже что-нибудь писать!

### Создание тензора

In [3]:
a = torch.FloatTensor([1, 2])
a


tensor([1., 2.])

In [4]:
a.shape

torch.Size([2])

In [5]:
b = torch.FloatTensor([[1,2,3], [4,5,6]])
b

tensor([[1., 2., 3.],
        [4., 5., 6.]])

In [6]:
b.shape

torch.Size([2, 3])

In [7]:
x = torch.FloatTensor(2,3,4)

In [8]:
x

tensor([[[0.0000e+00, 0.0000e+00, 0.0000e+00, 0.0000e+00],
         [0.0000e+00, 0.0000e+00, 0.0000e+00, 0.0000e+00],
         [0.0000e+00, 0.0000e+00, 2.0319e-43, 0.0000e+00]],

        [[1.9209e-04, 0.0000e+00, 6.8872e+07, 4.3222e-41],
         [0.0000e+00, 0.0000e+00, 0.0000e+00, 0.0000e+00],
         [0.0000e+00, 0.0000e+00, 0.0000e+00, 0.0000e+00]]])

In [9]:
x = torch.FloatTensor(100)
x

tensor([6.8876e+07, 4.3222e-41, 6.8876e+07, 4.3222e-41, 4.4842e-44, 0.0000e+00,
        1.1210e-43, 0.0000e+00, 1.9359e-04, 0.0000e+00, 2.4803e-43, 0.0000e+00,
        1.9207e-04, 0.0000e+00, 6.8872e+07, 4.3222e-41, 0.0000e+00, 0.0000e+00,
        0.0000e+00, 0.0000e+00, 0.0000e+00, 0.0000e+00, 0.0000e+00, 0.0000e+00,
        0.0000e+00, 0.0000e+00, 2.7045e-43, 0.0000e+00, 3.8546e-04, 0.0000e+00,
        6.8872e+07, 4.3222e-41, 1.9207e-04, 0.0000e+00, 1.9206e-04, 0.0000e+00,
        0.0000e+00, 0.0000e+00, 0.0000e+00, 0.0000e+00, 0.0000e+00, 0.0000e+00,
        0.0000e+00, 0.0000e+00, 0.0000e+00, 0.0000e+00, 1.5835e-43, 0.0000e+00,
        3.8549e-04, 0.0000e+00, 1.9204e-04, 0.0000e+00, 3.5873e-43, 0.0000e+00,
        1.5695e-43, 0.0000e+00, 1.9338e-04, 0.0000e+00, 0.0000e+00, 1.4013e-45,
        1.9208e-04, 0.0000e+00, 6.8664e-44, 0.0000e+00, 1.0104e-07, 0.0000e+00,
        1.9203e-04, 0.0000e+00, 0.0000e+00, 1.8053e+01, 0.0000e+00, 1.6942e-05,
        4.2599e-43, 0.0000e+00, 1.5695e-

In [10]:
x = torch.IntTensor(45, 57, 14, 2)
x.shape

torch.Size([45, 57, 14, 2])

**Примечание:** если вы создаете `torch.Tensor` с помощью следующего конструктора, он будет заполнен мусором из "случайных номеров":

In [11]:
x = torch.IntTensor(3, 2, 4)
x

tensor([[[969508370,         0,         0,         1],
         [       64,         0,        80,         0]],

        [[961214146,         0,         0,         0],
         [993090302,     30843, 993090303,     30843]],

        [[        0,         0,         0,         0],
         [       26,        -1, 869296556,         0]]], dtype=torch.int32)

### Инициализации тензоров

In [12]:
x1 = torch.FloatTensor(3, 2, 4)
x1.zero_()
x2 = torch.zeros(3, 2, 4)
x3 = torch.zeros_like(x1)

assert torch.allclose(x1, x2) and torch.allclose(x1, x3)

Инициализация случайного распределения

In [13]:
x = torch.randn((2,3))                # Normal(0, 1) с размером (2, 3)
x

tensor([[-1.2472,  0.4292,  0.3426],
        [-0.1882,  0.8385,  0.5148]])

In [14]:
x.random_(0, 10)                      # Дискретное равномерно U[0, 10]
x.uniform_(0, 1)                      # Равномерно U[0, 1]
x.normal_(mean=0, std=1)              # Нормальное со средним 0 и дисперсией 1
x.bernoulli_(p=0.5)                   # bernoulli with parameter p

tensor([[0., 1., 1.],
        [0., 1., 0.]])

## Функции в Torch

У всех функций Numpy есть своя пара в Torch! Осталось теперь вспомнить numpy 🙂

https://github.com/torch/torch7/wiki/Torch-for-Numpy-users

### Изменение формы
`np.reshape()` == `torch.view()`:

In [15]:
b

tensor([[1., 2., 3.],
        [4., 5., 6.]])

In [16]:
b.view(3, 2).shape

torch.Size([3, 2])

In [17]:
b

tensor([[1., 2., 3.],
        [4., 5., 6.]])

In [18]:
b, b.stride()

(tensor([[1., 2., 3.],
         [4., 5., 6.]]),
 (3, 1))

In [19]:
b.view(3, 2), b.view(3, 2).stride()

(tensor([[1., 2.],
         [3., 4.],
         [5., 6.]]),
 (2, 1))

**Примечание:** `torch.view ()` создает новый тензор, но старый остается неизменным

In [20]:
b.view(-1, 2)

tensor([[1., 2.],
        [3., 4.],
        [5., 6.]])

In [21]:
b

tensor([[1., 2., 3.],
        [4., 5., 6.]])

In [22]:
b.T.stride(), b.is_contiguous(), b.T.is_contiguous()

((1, 3), True, False)

<img src='https://lh3.googleusercontent.com/proxy/pbQ8C9YLVguU2LzlfE2-57lC3KK3yIRsQnpaTOK9S2UPpopvnZ3JhgeMcT6_kqYL56xq18ZFqddzPhszZg1W9YY--y-qDD2-bJrjVYivMdpQgRqiumwh6PpJYU3cL5Mua9RNeVp6xK0'>

In [23]:
b.reshape(-1) # возвращает view или contigues тензор

tensor([1., 2., 3., 4., 5., 6.])

In [24]:
b

tensor([[1., 2., 3.],
        [4., 5., 6.]])

### Изменение типа тензора

In [25]:
a = torch.FloatTensor([1.5, 3.2, -7])

In [26]:
a.type_as(torch.IntTensor())

tensor([ 1,  3, -7], dtype=torch.int32)

In [27]:
a.to(torch.int32)

tensor([ 1,  3, -7], dtype=torch.int32)

In [28]:
a.type_as(torch.ByteTensor())

tensor([  1,   3, 249], dtype=torch.uint8)

In [29]:
a.to(torch.uint8)

tensor([  1,   3, 249], dtype=torch.uint8)

**Note:** `.type_as()` creates a new tensor, the old one remains unchanged

In [30]:
a

tensor([ 1.5000,  3.2000, -7.0000])

* Indexing is just like in `NumPy`:

In [31]:
a = torch.FloatTensor([[100, 20, 35], [15, 163, 534], [52, 90, 66]])
a

tensor([[100.,  20.,  35.],
        [ 15., 163., 534.],
        [ 52.,  90.,  66.]])

In [32]:
a[0, 0]

tensor(100.)

In [33]:
a[0:2, 1]

tensor([ 20., 163.])

### Арифметические операции

| операция | аналоги |
|:-:|:-:|
|`+`| `torch.add()` |
|`-`| `torch.sub()` |
|`*`| `torch.mul()` |
|`/`| `torch.div()` |

#### Сложение

In [34]:
a = torch.FloatTensor([[1, 2, 3], [10, 20, 30], [100, 200, 300]])
b = torch.FloatTensor([[-1, -2, -3], [-10, -20, -30], [100, 200, 300]])

In [35]:
a + b

tensor([[  0.,   0.,   0.],
        [  0.,   0.,   0.],
        [200., 400., 600.]])

In [36]:
a.add(b)

tensor([[  0.,   0.,   0.],
        [  0.,   0.,   0.],
        [200., 400., 600.]])

In [37]:
b = -a
b

tensor([[  -1.,   -2.,   -3.],
        [ -10.,  -20.,  -30.],
        [-100., -200., -300.]])

In [38]:
a + b

tensor([[0., 0., 0.],
        [0., 0., 0.],
        [0., 0., 0.]])

#### Вычитание

In [39]:
a - b

tensor([[  2.,   4.,   6.],
        [ 20.,  40.,  60.],
        [200., 400., 600.]])

In [40]:
a.sub(b) # copy

tensor([[  2.,   4.,   6.],
        [ 20.,  40.,  60.],
        [200., 400., 600.]])

In [41]:
a.sub_(b) # inplace

tensor([[  2.,   4.,   6.],
        [ 20.,  40.,  60.],
        [200., 400., 600.]])

#### Умножение (поэлементное)

In [42]:
a * b

tensor([[-2.0000e+00, -8.0000e+00, -1.8000e+01],
        [-2.0000e+02, -8.0000e+02, -1.8000e+03],
        [-2.0000e+04, -8.0000e+04, -1.8000e+05]])

In [43]:
a.mul(b)

tensor([[-2.0000e+00, -8.0000e+00, -1.8000e+01],
        [-2.0000e+02, -8.0000e+02, -1.8000e+03],
        [-2.0000e+04, -8.0000e+04, -1.8000e+05]])

#### Деление (поэлементное):

In [44]:
a = torch.FloatTensor([[1, 2, 3], [10, 20, 30], [100, 200, 300]])
b = torch.FloatTensor([[-1, -2, -3], [-10, -20, -30], [100, 200, 300]])

In [45]:
a / b

tensor([[-1., -1., -1.],
        [-1., -1., -1.],
        [ 1.,  1.,  1.]])

In [46]:
a.div(b)

tensor([[-1., -1., -1.],
        [-1., -1., -1.],
        [ 1.,  1.,  1.]])

**Примечание:** все эти операции создают новые тензоры, старые тензоры остаются неизменными.

In [47]:
a

tensor([[  1.,   2.,   3.],
        [ 10.,  20.,  30.],
        [100., 200., 300.]])

In [48]:
b

tensor([[ -1.,  -2.,  -3.],
        [-10., -20., -30.],
        [100., 200., 300.]])

### Операторы сравнения

In [49]:
a = torch.FloatTensor([[1, 2, 3], [10, 20, 30], [100, 200, 300]])
b = torch.FloatTensor([[-1, -2, -3], [-10, -20, -30], [100, 200, 300]])

In [50]:
a == b

tensor([[False, False, False],
        [False, False, False],
        [ True,  True,  True]])

In [51]:
a != b

tensor([[ True,  True,  True],
        [ True,  True,  True],
        [False, False, False]])

In [52]:
a < b

tensor([[False, False, False],
        [False, False, False],
        [False, False, False]])

In [53]:
a > b

tensor([[ True,  True,  True],
        [ True,  True,  True],
        [False, False, False]])

### Использование индексации по логической маске

In [54]:
a[a > b]

tensor([ 1.,  2.,  3., 10., 20., 30.])

In [55]:
b[a == b]

tensor([100., 200., 300.])

### Поэлементное применение **универсальных функций**

In [56]:
a = torch.FloatTensor([[1, 2, 3], [10, 20, 30], [100, 200, 300]])

In [57]:
a.sin()

tensor([[ 0.8415,  0.9093,  0.1411],
        [-0.5440,  0.9129, -0.9880],
        [-0.5064, -0.8733, -0.9998]])

In [58]:
torch.sin(a)

tensor([[ 0.8415,  0.9093,  0.1411],
        [-0.5440,  0.9129, -0.9880],
        [-0.5064, -0.8733, -0.9998]])

In [59]:
a.tan()

tensor([[ 1.5574, -2.1850, -0.1425],
        [ 0.6484,  2.2372, -6.4053],
        [-0.5872, -1.7925, 45.2447]])

In [60]:
a.exp()

tensor([[2.7183e+00, 7.3891e+00, 2.0086e+01],
        [2.2026e+04, 4.8517e+08, 1.0686e+13],
        [       inf,        inf,        inf]])

In [61]:
a.log()

tensor([[0.0000, 0.6931, 1.0986],
        [2.3026, 2.9957, 3.4012],
        [4.6052, 5.2983, 5.7038]])

In [62]:
b = -a
b

tensor([[  -1.,   -2.,   -3.],
        [ -10.,  -20.,  -30.],
        [-100., -200., -300.]])

In [63]:
b.abs()

tensor([[  1.,   2.,   3.],
        [ 10.,  20.,  30.],
        [100., 200., 300.]])

### Агрегация и работа с осями
#### sum, mean, max, min:

In [64]:
a.sum(dim=1)

tensor([  6.,  60., 600.])

In [65]:
a.mean()

tensor(74.)

#### Применение функции вдоль оси

In [66]:
a

tensor([[  1.,   2.,   3.],
        [ 10.,  20.,  30.],
        [100., 200., 300.]])

In [67]:
a.sum(dim=0)

tensor([111., 222., 333.])

In [68]:
a.sum(dim=1)

tensor([  6.,  60., 600.])

In [69]:
a.max()

tensor(300.)

In [70]:
a.max(0)

torch.return_types.max(
values=tensor([100., 200., 300.]),
indices=tensor([2, 2, 2]))

**Примечание:** второй тензор, возвращаемый `.max()`, содержит индексы элементов max вдоль этой оси. Например. в этом случае `a.max ()` вернула `(100, 200, 300)`, которые являются минимальными элементами по оси 0 (вдоль столбцов), а их индексы по оси 0 равны `(2, 2, 2)`.


#### Фиктивные оси

Иногда очень сложно бывает разобраться, как правильно выбрать оси для применения операций с многомерными массивами. Поэтому сейчас мы решим на эту тему пару задач.
Сначала посмотрим, как создавать у массивов новые фиктивные оси, это нам пригодится.

In [71]:
a = torch.FloatTensor([[1, 2, 3], [10, 20, 30], [100, 200, 300]])

a[:, None, :].shape

torch.Size([3, 1, 3])

In [72]:
a[:, :, None]

tensor([[[  1.],
         [  2.],
         [  3.]],

        [[ 10.],
         [ 20.],
         [ 30.]],

        [[100.],
         [200.],
         [300.]]])

#### Безобидная задача на кумулятивные суммы
Дана матрица $M \times N$. Напишите функцию, которая возвращает вектор средних значений по вертикали.



In [73]:
def vertical_means(A):
    """
    param A: torch.tensor[m,n]
    """

    result = A.mean(dim=0)

    return result # <YOUR CODE>

A = torch.FloatTensor([[1, 4],
                       [2, 7]] )

vertical_means(A)

tensor([1.5000, 5.5000])

**Проблемы:**

* Что такое вертикальная ось?
* По какой оси необходимо суммировать?
* Как не ошибиться?

**Ответ:** Операции всегда производятся по той оси, которая **исчезнет** после применения операции.

#### Задача на нормализацию изображения
Реализуйте функцию ``normalize_pictures(A)``, которая принимает на вход четырёхмерный тензор --- батч из ``batch_size`` изображений, каждое из которых является трехмерным тензором формы (num_channels, width, height). Нужно стандартизировать изображение по каждому каналу, то есть сделать так, чтобы среднее значение яркости каждого канала (по всем изображениям и всем пикселям) было равно 0, а стандартное отклонение --- 1.

In [74]:
def normalize_pictures(A):
    """
    param A: torch.Tensor[batch_size, num_channels, width, height]
    """

    m = A.mean(dim=(2,3))
    sigma = A.std(dim =(2, 3))

    result = (A - m[:, :, None, None])/sigma[:, :, None, None]


    return result

In [75]:
batch = torch.randint(0, 156, (64, 3, 300, 300), dtype=torch.float32)
batch.mean(dim=(2,3)).shape

torch.Size([64, 3])

In [76]:
batch = torch.randint(0, 256, (64, 3, 300, 300), dtype=torch.float32)

B = normalize_pictures(batch)
# print(B.mean(dim=(2,3)).shape)
# print(B.std(dim=(2,3)))

## Матричные операции

#### Транспонирование тензора

In [77]:
a = torch.FloatTensor([[1, 2, 3], [10, 20, 30], [100, 200, 300]])
a

tensor([[  1.,   2.,   3.],
        [ 10.,  20.,  30.],
        [100., 200., 300.]])

In [78]:
a.t()

tensor([[  1.,  10., 100.],
        [  2.,  20., 200.],
        [  3.,  30., 300.]])

Это тоже не inplace-операция:

In [79]:
a

tensor([[  1.,   2.,   3.],
        [ 10.,  20.,  30.],
        [100., 200., 300.]])

#### Скалярное произведение векторов

In [80]:
a = torch.FloatTensor([1, 2, 3, 4, 5, 6])
b = torch.FloatTensor([-1, -2, -4, -6, -8, -10])

In [81]:
a.dot(b)

tensor(-141.)

In [82]:
a.shape, b.shape

(torch.Size([6]), torch.Size([6]))

In [83]:
a @ b

tensor(-141.)

In [84]:
type(a)

torch.Tensor

In [85]:
type(b)

torch.Tensor

In [86]:
type(a @ b)

torch.Tensor

#### Матричное произведение

In [87]:
a = torch.FloatTensor([[1, 2, 3], [10, 20, 30], [100, 200, 300]])
b = torch.FloatTensor([[-1, -2, -3], [-10, -20, -30], [100, 200, 300]])

In [88]:
a.mm(b)

tensor([[  279.,   558.,   837.],
        [ 2790.,  5580.,  8370.],
        [27900., 55800., 83700.]])

In [89]:
a @ b

tensor([[  279.,   558.,   837.],
        [ 2790.,  5580.,  8370.],
        [27900., 55800., 83700.]])

In [90]:
a = torch.FloatTensor([[1, 2, 3], [10, 20, 30], [100, 200, 300]])
b = torch.FloatTensor([[-1], [-10], [100]])

In [91]:
print(a.shape, b.shape)

torch.Size([3, 3]) torch.Size([3, 1])


In [92]:
a @ b

tensor([[  279.],
        [ 2790.],
        [27900.]])

Тензор `b` можно развернуть в одномерный массив с помощью функции `torch.view(-1)`, чтобы результат был вектором

In [93]:
b

tensor([[ -1.],
        [-10.],
        [100.]])

In [94]:
b.view(-1)

tensor([ -1., -10., 100.])

In [95]:
a @ b.view(-1)

tensor([  279.,  2790., 27900.])

In [96]:
a.mv(b.view(-1))

tensor([  279.,  2790., 27900.])

In [97]:
y = torch.Tensor(2, 3, 4, 5)
z = torch.Tensor(2, 3, 5, 6)
(y @ z).shape

torch.Size([2, 3, 4, 6])

## Конвертация
#### Конвертация из Numpy в Pytorch:

In [98]:
import numpy as np

a = np.random.rand(3, 3)
a

array([[0.55559591, 0.12832552, 0.41696086],
       [0.76090163, 0.09453499, 0.3544551 ],
       [0.08938814, 0.43557885, 0.68991973]])

In [99]:
b = torch.from_numpy(a)
b

tensor([[0.5556, 0.1283, 0.4170],
        [0.7609, 0.0945, 0.3545],
        [0.0894, 0.4356, 0.6899]], dtype=torch.float64)

**Внимание!** `a` и `b` хранятся в одной и той же ячейке данных. Если именить один тензор, то изменится и другой.

In [100]:
b -= b
b

tensor([[0., 0., 0.],
        [0., 0., 0.],
        [0., 0., 0.]], dtype=torch.float64)

In [101]:
a

array([[0., 0., 0.],
       [0., 0., 0.],
       [0., 0., 0.]])

#### Конвертация из Torch в Numpy

In [102]:
a = torch.FloatTensor(2, 3, 4)
a

tensor([[[3.9957e-04, 0.0000e+00, 3.8727e-04, 0.0000e+00],
         [1.1210e-43, 0.0000e+00, 8.9683e-44, 0.0000e+00],
         [3.2810e-04, 0.0000e+00, 0.0000e+00, 0.0000e+00]],

        [[0.0000e+00, 0.0000e+00, 0.0000e+00, 0.0000e+00],
         [1.4013e-45, 0.0000e+00, 0.0000e+00, 0.0000e+00],
         [0.0000e+00, 0.0000e+00, 1.5835e-43, 0.0000e+00]]])

In [103]:
type(a)

torch.Tensor

In [104]:
x = a.numpy()
x

array([[[3.9956858e-04, 0.0000000e+00, 3.8726581e-04, 0.0000000e+00],
        [1.1210388e-43, 0.0000000e+00, 8.9683102e-44, 0.0000000e+00],
        [3.2810491e-04, 0.0000000e+00, 0.0000000e+00, 0.0000000e+00]],

       [[0.0000000e+00, 0.0000000e+00, 0.0000000e+00, 0.0000000e+00],
        [1.4012985e-45, 0.0000000e+00, 0.0000000e+00, 0.0000000e+00],
        [0.0000000e+00, 0.0000000e+00, 1.5834673e-43, 0.0000000e+00]]],
      dtype=float32)

In [105]:
x.shape

(2, 3, 4)

In [106]:
type(x)

numpy.ndarray

In [107]:
x -= x

In [108]:
a

tensor([[[0., 0., 0., 0.],
         [0., 0., 0., 0.],
         [0., 0., 0., 0.]],

        [[0., 0., 0., 0.],
         [0., 0., 0., 0.],
         [0., 0., 0., 0.]]])

## <h1 style="text-align: center;"><a href="https://ru.wikipedia.org/wiki/CUDA">CUDA</a></h3>

CUDA --- это программно-аппаратная архитектура параллельных вычислений, которая позволяет существенно увеличить вычислительную производительность благодаря использованию графических процессоров фирмы Nvidia. Для нас CUDA --- это драйвер, который позволяет нам проводить вычисления на GPU.

[CUDA documentation](https://docs.nvidia.com/cuda/)

Для вычислений на Pytorch мы можем использовать как CPU (Central Processing Unit), так и GPU (Graphical Processing Unit). Между ними можно легко переключаться, и это очень важно!

In [109]:
x = torch.FloatTensor(1024, 10024).uniform_()
x

tensor([[0.7643, 0.5748, 0.7434,  ..., 0.3689, 0.2612, 0.8233],
        [0.6038, 0.2502, 0.4626,  ..., 0.4605, 0.5487, 0.0642],
        [0.9363, 0.7157, 0.2555,  ..., 0.3198, 0.8619, 0.5043],
        ...,
        [0.0328, 0.2075, 0.7630,  ..., 0.0553, 0.9147, 0.4452],
        [0.2287, 0.1794, 0.5255,  ..., 0.3873, 0.8542, 0.1320],
        [0.1969, 0.3689, 0.3768,  ..., 0.1778, 0.7534, 0.4377]])

In [110]:
x.is_cuda

False

#### Кладём тензор на GPU

In [111]:
!nvidia-smi

Mon Dec 15 16:00:08 2025       
+-----------------------------------------------------------------------------------------+
| NVIDIA-SMI 550.54.15              Driver Version: 550.54.15      CUDA Version: 12.4     |
|-----------------------------------------+------------------------+----------------------+
| GPU  Name                 Persistence-M | Bus-Id          Disp.A | Volatile Uncorr. ECC |
| Fan  Temp   Perf          Pwr:Usage/Cap |           Memory-Usage | GPU-Util  Compute M. |
|                                         |                        |               MIG M. |
|=========================================+========================+======================|
|   0  Tesla T4                       Off |   00000000:00:04.0 Off |                    0 |
| N/A   57C    P8             10W /   70W |       0MiB /  15360MiB |      0%      Default |
|                                         |                        |                  N/A |
+-----------------------------------------+-----

In [112]:
x = x.cuda()

In [113]:
!nvidia-smi

Mon Dec 15 16:00:09 2025       
+-----------------------------------------------------------------------------------------+
| NVIDIA-SMI 550.54.15              Driver Version: 550.54.15      CUDA Version: 12.4     |
|-----------------------------------------+------------------------+----------------------+
| GPU  Name                 Persistence-M | Bus-Id          Disp.A | Volatile Uncorr. ECC |
| Fan  Temp   Perf          Pwr:Usage/Cap |           Memory-Usage | GPU-Util  Compute M. |
|                                         |                        |               MIG M. |
|=========================================+========================+======================|
|   0  Tesla T4                       Off |   00000000:00:04.0 Off |                    0 |
| N/A   58C    P0             29W /   70W |     142MiB /  15360MiB |      2%      Default |
|                                         |                        |                  N/A |
+-----------------------------------------+-----

In [114]:
x

tensor([[0.7643, 0.5748, 0.7434,  ..., 0.3689, 0.2612, 0.8233],
        [0.6038, 0.2502, 0.4626,  ..., 0.4605, 0.5487, 0.0642],
        [0.9363, 0.7157, 0.2555,  ..., 0.3198, 0.8619, 0.5043],
        ...,
        [0.0328, 0.2075, 0.7630,  ..., 0.0553, 0.9147, 0.4452],
        [0.2287, 0.1794, 0.5255,  ..., 0.3873, 0.8542, 0.1320],
        [0.1969, 0.3689, 0.3768,  ..., 0.1778, 0.7534, 0.4377]],
       device='cuda:0')

In [115]:
x = x.cpu()
!nvidia-smi

torch.cuda.empty_cache()
!nvidia-smi

Mon Dec 15 16:00:09 2025       
+-----------------------------------------------------------------------------------------+
| NVIDIA-SMI 550.54.15              Driver Version: 550.54.15      CUDA Version: 12.4     |
|-----------------------------------------+------------------------+----------------------+
| GPU  Name                 Persistence-M | Bus-Id          Disp.A | Volatile Uncorr. ECC |
| Fan  Temp   Perf          Pwr:Usage/Cap |           Memory-Usage | GPU-Util  Compute M. |
|                                         |                        |               MIG M. |
|=========================================+========================+======================|
|   0  Tesla T4                       Off |   00000000:00:04.0 Off |                    0 |
| N/A   58C    P0             29W /   70W |     160MiB /  15360MiB |      0%      Default |
|                                         |                        |                  N/A |
+-----------------------------------------+-----

In [116]:
device = torch.device("cuda:0") if torch.cuda.is_available() else torch.device("cpu")

x = x.to(device)
x

tensor([[0.7643, 0.5748, 0.7434,  ..., 0.3689, 0.2612, 0.8233],
        [0.6038, 0.2502, 0.4626,  ..., 0.4605, 0.5487, 0.0642],
        [0.9363, 0.7157, 0.2555,  ..., 0.3198, 0.8619, 0.5043],
        ...,
        [0.0328, 0.2075, 0.7630,  ..., 0.0553, 0.9147, 0.4452],
        [0.2287, 0.1794, 0.5255,  ..., 0.3873, 0.8542, 0.1320],
        [0.1969, 0.3689, 0.3768,  ..., 0.1778, 0.7534, 0.4377]],
       device='cuda:0')

Умножим два тензора в GPU и вернём результат обратно на CPU:

In [117]:
a = torch.FloatTensor(10000, 10000).uniform_()
b = torch.FloatTensor(10000, 10000).uniform_()
c = a.cuda().mul(b.cuda()).cpu()

In [118]:
c

tensor([[3.8443e-04, 1.2690e-01, 2.2724e-02,  ..., 1.8557e-01, 2.9097e-01,
         1.2190e-01],
        [6.1282e-01, 3.1990e-01, 4.4668e-01,  ..., 3.3901e-02, 6.0686e-02,
         2.1037e-01],
        [8.0106e-03, 4.5429e-01, 2.1959e-02,  ..., 2.4203e-01, 8.1562e-01,
         2.1529e-01],
        ...,
        [3.0970e-01, 5.5621e-02, 9.3236e-02,  ..., 6.1983e-01, 7.8933e-01,
         1.2621e-01],
        [3.7371e-01, 2.2200e-01, 3.0324e-01,  ..., 4.7864e-01, 7.7706e-01,
         3.2394e-02],
        [2.7286e-01, 1.1477e-01, 3.0712e-01,  ..., 6.3688e-01, 9.8514e-02,
         2.1907e-01]])

In [119]:
a

tensor([[7.1579e-04, 6.4073e-01, 1.7009e-01,  ..., 6.7150e-01, 6.2746e-01,
         1.3741e-01],
        [9.2243e-01, 3.7838e-01, 5.2137e-01,  ..., 2.8872e-01, 2.3129e-01,
         3.0509e-01],
        [1.6266e-02, 7.1609e-01, 2.7416e-01,  ..., 3.3752e-01, 8.1998e-01,
         3.8999e-01],
        ...,
        [9.9077e-01, 1.2872e-01, 1.6617e-01,  ..., 7.1599e-01, 9.3880e-01,
         4.2629e-01],
        [5.3710e-01, 5.0198e-01, 4.9949e-01,  ..., 9.7492e-01, 8.2751e-01,
         1.3672e-01],
        [3.9975e-01, 1.6006e-01, 7.1099e-01,  ..., 7.2187e-01, 2.7082e-01,
         8.7849e-01]])

Тензоры из разных областей памяти не совместимы:

In [120]:
a = torch.FloatTensor(10000, 10000).uniform_().cpu()
b = torch.FloatTensor(10000, 10000).uniform_().cuda()

In [121]:
a + b

RuntimeError: Expected all tensors to be on the same device, but found at least two devices, cuda:0 and cpu!

### Пример работы на GPU

In [122]:
device = 'cuda' if torch.cuda.is_available() else 'cpu'

In [123]:
x = torch.FloatTensor(5, 5, 5).uniform_()

# проверить наличие CUDA (NVIDIA GPU)
if torch.cuda.is_available():
    # получить имя устройства CUDA
    device = torch.device('cuda')          # Объект CUDA-устройства
    y = torch.ones_like(x, device=device)  # создаем тензор на GPU
    x = x.to(device)                       # или просто `.to("cuda")`
    z = x + y
    print(z)
    # вы можете установить тип во время операции `.to`
    print(z.to("cpu", torch.double))

tensor([[[1.9900, 1.0147, 1.1122, 1.0241, 1.9383],
         [1.3921, 1.0951, 1.0911, 1.3798, 1.9030],
         [1.4888, 1.4903, 1.9063, 1.0202, 1.6717],
         [1.7391, 1.5749, 1.7311, 1.0277, 1.7431],
         [1.7178, 1.5142, 1.6202, 1.0886, 1.8633]],

        [[1.1473, 1.1135, 1.6708, 1.4307, 1.8264],
         [1.1167, 1.4773, 1.4205, 1.2706, 1.4076],
         [1.8515, 1.7856, 1.0694, 1.4788, 1.6848],
         [1.8995, 1.5329, 1.9411, 1.8707, 1.0376],
         [1.2694, 1.6729, 1.3280, 1.1519, 1.3869]],

        [[1.4479, 1.4448, 1.1660, 1.9708, 1.5430],
         [1.0487, 1.4358, 1.8155, 1.7240, 1.7054],
         [1.4696, 1.0589, 1.2019, 1.7819, 1.5289],
         [1.7191, 1.7424, 1.8252, 1.1648, 1.7789],
         [1.1494, 1.4689, 1.1223, 1.7916, 1.4067]],

        [[1.9245, 1.6360, 1.5398, 1.9298, 1.9778],
         [1.2032, 1.3986, 1.5453, 1.4546, 1.4930],
         [1.4102, 1.5564, 1.1179, 1.7443, 1.6890],
         [1.4126, 1.8679, 1.0284, 1.4553, 1.9772],
         [1.7496, 1.5120,